# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: cfn-look-up-amis-ids

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs4.3
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
      Resource: "arn:aws:logs:*:*:*"
    - Effect: "Allow"
      Action:
        - "ec2:DescribeImages"
      Resource: "*"

package:
  include:
    - serverless.yml
    - index.js

# The `functions` block defines what code to deploy
functions:
  cfn-look-up-amis-ids:
    handler: index.handler
    # # The `events` block defines how to trigger the handler.helloWorld code
    # events:
    #   - http:
    #       path: hello-world
    #       method: get
    #       cors: true
